### ISSUE TITLE
org.eclipse.rdf4j.query.QueryEvaluationException: Tag mismatch!

### ISSUE THREAD

**Issue by skang2023** [aws/neptune-export#43] opened 2023-06-29 13:43 UTC
Hi I was using Neptune export and got the following error while exporting the entire graphs in the rdf format. 

Please see below for the the export parameter set I used for the export job. Please note that the exact URI of 'subject','object','predicate' was sanitized: 

```
export_params={ 
    "command": "export-rdf",
    "params": {
        "endpoint": neptune_ml.get_host(),
        "useIamAuth": neptune_ml.get_iam(),
        "cloneCluster": False,
        "profile": "neptune_ml"
    },
    "outputS3Path": f'{s3_bucket_uri}/neptune-export',
    "additionalParams": {
        "neptune_ml": {
            "version": "v2.0",
            "targets": [
                {
                    "subject" : "subject(sanitized)",
                    "predicate" : "predicate(sanitized)",
                    "object" : "object(sanitized)",
                    "type": "link_prediction",
                    "split_rate": [0.99, 0.01, 0.00]
                }
            ]
        }
    },
    "jobSize": "large"

 ```

And it fails with the error message as shown below 

CloudWatch excerpt showing the part where the process failed with QueryEvaluationExceptionError (see the last line):
```
(...)
An error occurred   while exporting RDF edges as NTRIPLES. Elapsed time: 627 seconds
--

An error occurred while exporting rdf   edges. Elapsed time: 1977 seconds
java.lang.RuntimeException:
at   com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeGraphQuery(NeptuneSparqlClient.java:145)
at   com.amazonaws.services.neptune.rdf.ExportRdfEdgesJob.lambda$execute$0(ExportRdfEdgesJob.java:35)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
at   com.amazonaws.services.neptune.rdf.ExportRdfEdgesJob.execute(ExportRdfEdgesJob.java:31)
at   com.amazonaws.services.neptune.ExportRdfGraph.lambda$run$0(ExportRdfGraph.java:77)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
at   com.amazonaws.services.neptune.ExportRdfGraph.run(ExportRdfGraph.java:60)
at   com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:72)
at   com.amazonaws.services.neptune.export.NeptuneExportService.execute(NeptuneExportService.java:235)
at   com.amazonaws.services.neptune.export.NeptuneExportLambda.handleRequest(NeptuneExportLambda.java:173)
at   com.amazonaws.services.neptune.RunNeptuneExportSvc.run(RunNeptuneExportSvc.java:60)
at   com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:72)
at   com.amazonaws.services.neptune.NeptuneExportCli.main(NeptuneExportCli.java:48)
Caused by:   org.eclipse.rdf4j.query.QueryEvaluationException: Tag mismatch!
(...)

```
Here are other Java errors from the same CW Logs with the same message:
```

... 15 more
**Caused by:   javax.crypto.AEADBadTagException: Tag mismatch!**
at   com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620)
at   com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
at   com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at   com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
at   com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
at   javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
at   javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
at   javax.crypto.Cipher.doFinal(Cipher.java:2463)
at   sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1606)
at   sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
at   sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
at   sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
```

```
(...)

Caused by:   javax.net.ssl.SSLException: Tag mismatch!
--
at   sun.security.ssl.Alert.createSSLException(Alert.java:133)
at   sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
at   sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
at   sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
at   sun.security.ssl.SSLTransport.decode(SSLTransport.java:119)
at   sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1400)
at   sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1368)
at   sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
at   sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:962)
at   org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at   org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at   org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
at   org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
at   org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
at   org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
at   org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at   org.apache.commons.io.input.BOMInputStream.read(BOMInputStream.java:335)
at   sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
at   sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
at   sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
at   sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
at   sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
at   java.io.InputStreamReader.read(InputStreamReader.java:168)
at   java.io.FilterReader.read(FilterReader.java:65)
at   java.io.PushbackReader.read(PushbackReader.java:90)
(...)
```

However, when I limit the results to a specific subset of the data, it succeeds. See the additional sparql extract in the code block below. Please note that the exact URI of 'subject','object','predicate' was sanitized but they were the same as those used in ``export_params`` above. 

```
export_params2 = { 
    "command": "export-rdf",
    "params": {
        "endpoint": neptune_ml.get_host(),
        "useIamAuth": neptune_ml.get_iam(),
        "cloneCluster": False,
        "profile": "neptune_ml",
        "format": "ntriples",
        "rdfExportScope" : "query",
        "sparql" : "SELECT * FROM NAMED <http://aws.amazon.com/neptune/vocab/v01/DefaultNamedGraph> WHERE { GRAPH ?g {?s a rdfclass(sanitized) . ?s ?p ?o}} limit 1000",
    },
    "outputS3Path": f'{s3_bucket_uri}/neptune-export',
    "additionalParams": {
        "neptune_ml": {
            "version": "v2.0",
            "targets": [
                {
                    "subject" : "subject(sanitized)",
                    "predicate" : "predicate(sanitized)",
                    "object" : "object(sanitized)",
                    "type": "link_prediction"
                }
            ]
        }
    },
    "jobSize": "large"
}
```

Since the cluster has shown success with the export job, I believe the Neptune cluster configuration is not the cause here. I was wondering what seems to be causing that "TagMismatch!" exception error and how we can identify/fix the issue. Thanks!

**Comment by Cole-Greer** [comment] 2023-06-30 02:04
Hi @skang2023,

I'm taking a look at your error messages, could you provide the remaining stack trace for the `QueryEvaluationException` from your first log excerpt you shared? Also if there are any additional nested "Caused by:" exceptions could you include those as well? Also could you confirm that your sanitized data has no un-escaped angle brackets in it and that the `neptune_query_timeout` in your neptune parameter group is sufficiently large?

I hope that this will help identify source of the mismatched tags which are preventing your data from parsing.

Thanks,
Cole

**Comment by skang2023** [comment] 2023-06-30 03:04
Hi @Cole-Greer ,

There was not much in the log other than those errors themselves. Please see below for what comes before and after those. It contains all three blocks I pasted in the original post. 

Also confirming that the sanitized uris do not have any escape symbols and  ``neptune_query_timeout`` is currently set as 27 hours.  

Best,
Shinae 
``` 
(...)
An error occurred   while exporting rdf edges. Elapsed time: 1977 seconds
--
java.lang.RuntimeException:
at   com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeGraphQuery(NeptuneSparqlClient.java:145)
at   com.amazonaws.services.neptune.rdf.ExportRdfEdgesJob.lambda$execute$0(ExportRdfEdgesJob.java:35)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
at   com.amazonaws.services.neptune.rdf.ExportRdfEdgesJob.execute(ExportRdfEdgesJob.java:31)
at   com.amazonaws.services.neptune.ExportRdfGraph.lambda$run$0(ExportRdfGraph.java:77)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:41)
at   com.amazonaws.services.neptune.util.Timer.timedActivity(Timer.java:34)
at   com.amazonaws.services.neptune.ExportRdfGraph.run(ExportRdfGraph.java:60)
at   com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:72)
at   com.amazonaws.services.neptune.export.NeptuneExportService.execute(NeptuneExportService.java:235)
at   com.amazonaws.services.neptune.export.NeptuneExportLambda.handleRequest(NeptuneExportLambda.java:173)
at   com.amazonaws.services.neptune.RunNeptuneExportSvc.run(RunNeptuneExportSvc.java:60)
at   com.amazonaws.services.neptune.export.NeptuneExportRunner.run(NeptuneExportRunner.java:72)
at   com.amazonaws.services.neptune.NeptuneExportCli.main(NeptuneExportCli.java:48)
Caused by:   org.eclipse.rdf4j.query.QueryEvaluationException: Tag mismatch!
at   org.eclipse.rdf4j.repository.sparql.query.SPARQLGraphQuery.evaluate(SPARQLGraphQuery.java:57)
at   com.amazonaws.services.neptune.rdf.NeptuneSparqlClient.executeGraphQuery(NeptuneSparqlClient.java:141)
... 14 more
Caused by: javax.net.ssl.SSLException:   Tag mismatch!
at   sun.security.ssl.Alert.createSSLException(Alert.java:133)
at   sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
at   sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
at   sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
at   sun.security.ssl.SSLTransport.decode(SSLTransport.java:119)
at   sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1400)
at   sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1368)
at   sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
at   sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:962)
at   org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at   org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at   org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
at   org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
at   org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
at   org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
at   org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at   org.apache.commons.io.input.BOMInputStream.read(BOMInputStream.java:335)
at   sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
at   sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
at   sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
at   sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
at   sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
at   java.io.InputStreamReader.read(InputStreamReader.java:168)
at   java.io.FilterReader.read(FilterReader.java:65)
at   java.io.PushbackReader.read(PushbackReader.java:90)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.readCodePoint(TurtleParser.java:1205)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parseURI(TurtleParser.java:875)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:557)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:439)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:372)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:340)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:327)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:194)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:156)
at   org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(TurtleParser.java:119)
at   org.eclipse.rdf4j.http.client.SPARQLProtocolSession.getRDF(SPARQLProtocolSession.java:862)
at   org.eclipse.rdf4j.http.client.SPARQLProtocolSession.sendGraphQuery(SPARQLProtocolSession.java:421)
at   org.eclipse.rdf4j.repository.sparql.query.SPARQLGraphQuery.evaluate(SPARQLGraphQuery.java:54)
... 15 more
Caused by:   javax.crypto.AEADBadTagException: Tag mismatch!
at   com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620)
at   com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
at   com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at   com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941)
at   com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491)
at   javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779)
at   javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
at   javax.crypto.Cipher.doFinal(Cipher.java:2463)
at   sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1606)
at   sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262)
at   sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
at   sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
... 48 more
[main] WARN   com.amazonaws.services.neptune.export.ExportToS3NeptuneExportEventHandler -   Uploading results of failed export to S3
[main] WARN   com.amazonaws.services.neptune.export.ExportToS3NeptuneExportEventHandler -   Total size of failed export files: 7 GB
(...)
```

**Comment by Cole-Greer** [comment] 2023-06-30 23:04
Thanks @skang2023, this helps a lot. There seems to be an issue checking authentication tags. I will keep looking into this and keep you posted with any findings. Could I also ask what build and version of Java you are using for these tests?

Thanks,
Cole

**Comment by skang2023** [comment] 2023-07-03 14:37
Hi @Cole-Greer , I will share the Java version as soon as I find out. Please let me know if there are other things that might be helpful in finding the root cause of the error. Thanks!

**Comment by skang2023** [comment] 2023-07-03 18:44
Just wanted to add one thing: It is still puzzling because it has succeeded on a different condition (smaller dataset). If it is some error attributed to authentication, why was the attempt to export a smaller batch successful?

**Comment by Cole-Greer** [comment] 2023-07-04 22:44
Hi @skang2023, I also found the success on the smaller dataset a bit puzzling although I may have found an explanation. One more question I wanted to ask is if that error is something which you have seen repeatedly, or if it only happens infrequently or just the one time?

The `Tag mismatch` referenced in the error here is stating that the TLS message authentication code for a certain block of the message is incorrect. Usually this would indicate that some 3rd party has tampered with the message in flight although I don't believe this to be the case here. It seems likely to be related to [a synchronization issue](https://bugs.openjdk.org/browse/JDK-8277970) in the JDK SSL implementation. If this is the issue you are facing, I would expect it to be a very rare failure, although the odds of failure would increase at high data transfer rates.

Based on the stack trace you provided, it appears you are running some version of Java 8. A fix to the JDK issue I mentioned has been [backported to Java 11.0.18](https://bugs.openjdk.org/browse/JDK-8296473), although it does not appear to have been fixed in any version of Java 8. If this is the true cause of your issue, then an upgrade to Java 11.0.18 or later should resolve any issues.

**Comment by skang2023** [comment] 2023-07-05 13:33
Hi @Cole-Greer , thanks for the response.

For your question about the error frequency, yes this error has occurred consistently when I attempted to export the whole graph (3 or 4 times) and a coworker verified the same error on the same condition (same export parameter).  Because an export itself is successful on a specific condition, I was assuming that there was something in our data that triggers this error. 

I will see if we can easily upgrade the java and if this error can be fixed. We are using the Java Version that came with Amazon Neptune.. so not sure if we can easily update only the Java from our end. 

Lastly, confirming that we are using Java 8 as listed as the requirement in the official Neptune documentation (https://docs.aws.amazon.com/neptune/latest/userguide/export-utility.html).

**Comment by skang2023** [comment] 2023-07-05 13:59
Also, could this the issue I am facing for the Neptune Export related to this? https://github.com/corretto/corretto-8/issues/424 If so, would upgrade to Java11 or later version solve it as well? Thanks again for your help, @Cole-Greer !

**Comment by Cole-Greer** [comment] 2023-07-05 17:16
@skang2023 My initial assumption was also that something in your data was leading to this error but based on where the failure is taking place that seems unlikely now. I do believe that https://github.com/corretto/corretto-8/issues/424 is related to your issue. If that is the case, I would recommend upgrading to the latest corretto-11 (11.0.19) as this includes a patch for that issue. (I wouldn't recommend anything above Java 11, many of Neptune Export's dependencies aren't tested above Java 11 at this time) Let me know if you run into any issues with the upgrade as well as the results of running on Java 11.

**Comment by Cole-Greer** [comment] 2023-09-18 21:35
This error appears to occur when performing a large export from an undersized instance. This can be resolved by scaling up the Neptune cluster or by configuring the export job to export from a large cloned cluster.

```
"params": {
    "cloneCluster": True,
    "cloneClusterInstanceType" : "r5.24xlarge"
}
```
or
```
--clone-cluster --clone-cluster-instance-type r5.24xlarge
```
The list of supported instance types can be found here: https://github.com/aws/neptune-export/blob/8265ef71f05c6948569720a5a0684de3feb2383d/docs/export-rdf.md?plain=1#L55C16-L55C16

**Closed as completed** 2023-09-22 22:07 UTC
